//! [`BlockPalette`]: pick the block that looks most like a colour.
//!
//! Turning an image or a gradient into blocks means answering "which block is
//! this pixel?" thousands of times, so the four vanilla 16-colour families come
//! pre-tabulated, and the match runs in [`Oklab`](super::Oklab) — nearest by
//! *perceptual* distance, not by RGB coordinates, which is the difference
//! between a readable gradient and a muddy one.
//!
//! **Where the colours come from.** Each entry is the commonly cited average
//! texture colour of that block, as circulated in the community's map-art
//! palettes: the wool and stained-glass tables are the vanilla dye colours
//! (glass is a dye tint of the same 16 hues), concrete and terracotta are their
//! own flat texture colours. They are approximations by nature — a texture is
//! not one colour — and exactness matters far less than consistency, so all
//! four tables are curated in the same style rather than mixing sources.
//!
//! # Cost
//!
//! sRGB→Oklab needs three `powf`s and three `cbrt`s per colour, and those are
//! *software* routines inside the plugin's interpreter — expensive enough that
//! converting a whole table per lookup will exhaust a tick's instruction budget.
//! So every palette stores its entries' Oklab alongside the colour, computed
//! once: [`nearest`](BlockPalette::nearest) converts the query colour and
//! nothing else, then walks the table doing three subtractions and three
//! multiplications each.
//!
//! The vanilla tables carry their Oklab as constants (a `const fn` cannot call
//! `cbrt`), generated by running [`Color::to_oklab`] on the host and pasted in;
//! `stored_oklab_matches_the_conversion` re-derives all 64 of them on every test
//! run, so they cannot drift from the conversion they came from. User palettes
//! convert once in [`BlockPalette::new`].

use std::borrow::Cow;

use super::color::{Color, Oklab};
use crate::registry::{BlockId, blocks};

/// One palette entry: a colour, that colour in [`Oklab`], and the block that
/// wears it.
///
/// The Oklab is not redundant — it is the whole point. Matching is done in
/// Oklab, and converting is expensive, so every palette pays that cost once per
/// entry rather than once per lookup.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PaletteEntry {
    /// The block's tabulated sRGB colour.
    pub color: Color,
    /// `color`, converted to Oklab.
    pub oklab: Oklab,
    /// The block itself.
    pub block: BlockId,
}

impl PaletteEntry {
    /// Build an entry, converting the colour to Oklab once.
    pub fn new(color: Color, block: BlockId) -> PaletteEntry {
        PaletteEntry {
            color,
            oklab: color.to_oklab(),
            block,
        }
    }
}

/// A set of colours to match blocks against.
///
/// Use one of the four vanilla tables — [`CONCRETE`](BlockPalette::CONCRETE),
/// [`WOOL`](BlockPalette::WOOL), [`TERRACOTTA`](BlockPalette::TERRACOTTA),
/// [`GLASS`](BlockPalette::GLASS) — or build your own from any slice, including
/// a mix of families or a deliberately restricted set:
///
/// ```ignore
/// let duotone = BlockPalette::new(&[
///     (Color::rgb_hex(0x080A0F), blocks::BLACK_CONCRETE),
///     (Color::rgb_hex(0xCFD5D6), blocks::WHITE_CONCRETE),
/// ]);
/// let block = duotone.nearest(pixel);
/// ```
///
/// The vanilla tables are borrowed statics and cost nothing to name; a palette
/// built with [`new`](BlockPalette::new) owns its converted entries. Build it
/// once, outside your loop.
#[derive(Clone, Debug, PartialEq)]
pub struct BlockPalette {
    entries: Cow<'static, [PaletteEntry]>,
}

impl BlockPalette {
    /// A palette over `(colour, block)` pairs, converting each colour to Oklab
    /// once, here, so lookups don't.
    ///
    /// Empty palettes have no answer to give and kill the animation at
    /// [`nearest`](BlockPalette::nearest).
    pub fn new(entries: &[(Color, BlockId)]) -> BlockPalette {
        BlockPalette {
            entries: Cow::Owned(
                entries
                    .iter()
                    .map(|(color, block)| PaletteEntry::new(*color, *block))
                    .collect(),
            ),
        }
    }

    /// A palette over entries that already carry their Oklab — how the vanilla
    /// tables are built, and how you would wrap your own generated table.
    pub const fn from_entries(entries: &'static [PaletteEntry]) -> BlockPalette {
        BlockPalette {
            entries: Cow::Borrowed(entries),
        }
    }

    /// The entries, in table order.
    pub fn entries(&self) -> &[PaletteEntry] {
        &self.entries
    }

    /// The block whose tabulated colour is perceptually closest to `color`.
    /// Alpha is ignored — a block is opaque.
    ///
    /// One sRGB→Oklab conversion (the query) plus a squared-distance compare per
    /// entry. Ties go to the earlier entry, so the answer is stable across runs.
    pub fn nearest(&self, color: Color) -> BlockId {
        self.nearest_entry(color).block
    }

    /// [`nearest`](BlockPalette::nearest) plus the palette colour it matched,
    /// for when you want to know how far off the match was.
    pub fn nearest_with(&self, color: Color) -> (Color, BlockId) {
        let entry = self.nearest_entry(color);
        (entry.color, entry.block)
    }

    /// The whole matched entry, Oklab included.
    pub fn nearest_entry(&self, color: Color) -> PaletteEntry {
        self.nearest_to_oklab(color.to_oklab())
    }

    /// Match against a colour already in Oklab — no conversion at all.
    ///
    /// For pipelines that are already working perceptually (sampling a
    /// [`Gradient`](super::Gradient) and immediately matching it, say), this
    /// skips a round trip through sRGB and back.
    pub fn nearest_to_oklab(&self, target: Oklab) -> PaletteEntry {
        assert!(
            !self.entries.is_empty(),
            "BlockPalette::nearest called on an empty palette"
        );
        let mut best = self.entries[0];
        let mut best_d = best.oklab.distance_squared(target);
        for entry in &self.entries[1..] {
            let d = entry.oklab.distance_squared(target);
            if d < best_d {
                best = *entry;
                best_d = d;
            }
        }
        best
    }

    /// Every palette colour in Oklab — already stored, so this just copies.
    pub fn oklab_table(&self) -> Vec<Oklab> {
        self.entries.iter().map(|e| e.oklab).collect()
    }
}

/// Builds one of the vanilla 16-colour tables in vanilla dye order (white →
/// black): `0xRRGGBB, (l, a, b) => BLOCK_CONST`.
///
/// The Oklab triple is the paste-in of `Color::rgb_hex(0xRRGGBB).to_oklab()` —
/// see the module docs, and the test that keeps every one of them honest. Block
/// consts are spelled out rather than stitched together from a dye plus a
/// family, so every entry is a real compile-time reference into the generated
/// registry.
macro_rules! vanilla_table {
    ($name:ident, [$($hex:literal, ($l:literal, $a:literal, $b:literal) => $block:ident),+ $(,)?]) => {
        const $name: [PaletteEntry; 16] = [
            $(PaletteEntry {
                color: Color::rgb_hex($hex),
                oklab: Oklab::new($l, $a, $b),
                block: blocks::$block,
            }),+
        ];
    };
}

// The 16 dyes, per family. Concrete is the go-to for solid colour work;
// terracotta is the muted set; wool and glass share the dye hues.
vanilla_table!(CONCRETE_TABLE, [
    0xCFD5D6, (0.8686732564113188, -0.005873091000062669, -0.003226108475649525) => WHITE_CONCRETE,
    0xE06100, (0.6421146671197111, 0.12275939513999526, 0.1298891424804015) => ORANGE_CONCRETE,
    0xA9309F, (0.5333827269922813, 0.17432159636439715, -0.0944011738940419) => MAGENTA_CONCRETE,
    0x2489C7, (0.6036849409182755, -0.06135616136107924, -0.11357251757197634) => LIGHT_BLUE_CONCRETE,
    0xF1AF15, (0.7953619364103273, 0.02638467060993943, 0.1588299251606256) => YELLOW_CONCRETE,
    0x5EA918, (0.6603397549695015, -0.1280494953473748, 0.1305498138581847) => LIME_CONCRETE,
    0xD5658F, (0.6527674177230173, 0.14723055151053765, -0.004262579242285569) => PINK_CONCRETE,
    0x36393D, (0.34320682952557474, -0.0020220272860730637, -0.007846153323756988) => GRAY_CONCRETE,
    0x7D7D73, (0.586683630122226, -0.004317946640685522, 0.014256719008171825) => LIGHT_GRAY_CONCRETE,
    0x157788, (0.5248625123654826, -0.07272310416849559, -0.04713663981856492) => CYAN_CONCRETE,
    0x64209C, (0.41818889895861616, 0.10400000662189307, -0.15417973271007113) => PURPLE_CONCRETE,
    0x2C2E8F, (0.36807634057847227, 0.012806236922543679, -0.15545752897090032) => BLUE_CONCRETE,
    0x603C20, (0.39233476468884704, 0.03553224389656387, 0.05509439515943726) => BROWN_CONCRETE,
    0x495B24, (0.44283981195224, -0.04713137920128693, 0.06778015688759059) => GREEN_CONCRETE,
    0x8E2121, (0.4285536799652333, 0.1304227077737098, 0.06304428189410366) => RED_CONCRETE,
    0x080A0F, (0.144912051606444, -0.0006316437360297245, -0.011466105075472313) => BLACK_CONCRETE,
]);
vanilla_table!(WOOL_TABLE, [
    0xF9FFFE, (0.9952267541729087, -0.00642632041602853, -0.0005938072511147974) => WHITE_WOOL,
    0xF9801D, (0.7243783540040456, 0.10785301066727876, 0.1400023236447629) => ORANGE_WOOL,
    0xC74EBD, (0.6227896964098021, 0.1750229577568611, -0.09681189305140575) => MAGENTA_WOOL,
    0x3AB3DA, (0.7171404949734929, -0.08476154599521918, -0.08174782528386948) => LIGHT_BLUE_WOOL,
    0xFED83D, (0.889626794971553, -0.012918621783681361, 0.16548847521319687) => YELLOW_WOOL,
    0x80C71F, (0.7539833519404685, -0.13059133446238042, 0.14882514274629383) => LIME_WOOL,
    0xF38BAA, (0.7561702798344626, 0.1302555789211447, 0.003546876511352992) => PINK_WOOL,
    0x474F52, (0.4215182826075246, -0.008477561464597383, -0.0077006425756998564) => GRAY_WOOL,
    0x9D9D97, (0.6942210219300027, -0.00246243700956128, 0.008248676306012115) => LIGHT_GRAY_WOOL,
    0x169C9C, (0.6289937879664972, -0.10020612533512313, -0.026550547822836723) => CYAN_WOOL,
    0x8932B8, (0.5057857244127223, 0.133054633364054, -0.1542999468207395) => PURPLE_WOOL,
    0x3C44AA, (0.44260869437579925, 0.012151966789098245, -0.1607448804041251) => BLUE_WOOL,
    0x835432, (0.49074718859118327, 0.044839507955902136, 0.06537635347483084) => BROWN_WOOL,
    0x5E7C16, (0.5437072433306326, -0.07437223489521824, 0.10444141712664567) => GREEN_WOOL,
    0xB02E26, (0.5036981199495045, 0.1479264776559768, 0.07962232845020062) => RED_WOOL,
    0x1D1D21, (0.23244899610481348, 0.0020757759378686874, -0.0073398273328574015) => BLACK_WOOL,
]);
vanilla_table!(TERRACOTTA_TABLE, [
    0xD1B1A1, (0.784092323119113, 0.029012211375474717, 0.03238450647967572) => WHITE_TERRACOTTA,
    0xA05325, (0.5272905734517775, 0.07772715874639613, 0.08830888534527964) => ORANGE_TERRACOTTA,
    0x95576C, (0.5338846365329174, 0.0857861872859571, -0.001999568136552665) => MAGENTA_TERRACOTTA,
    0x706C8A, (0.5460209706177711, 0.016568310098338812, -0.04341995654752456) => LIGHT_BLUE_TERRACOTTA,
    0xBA8524, (0.6534300701110672, 0.027143212803797945, 0.12157067218191947) => YELLOW_TERRACOTTA,
    0x677535, (0.5358789658645495, -0.04475558043529329, 0.07822873495198296) => LIME_TERRACOTTA,
    0xA14E4E, (0.5271372152091931, 0.10271460234701307, 0.04053785823881123) => PINK_TERRACOTTA,
    0x392B24, (0.3028978722686702, 0.016257446077749843, 0.017992941675843727) => GRAY_TERRACOTTA,
    0x876B62, (0.5526849419800285, 0.0301351079450064, 0.024031880641822212) => LIGHT_GRAY_TERRACOTTA,
    0x575B5B, (0.46760646821295626, -0.004857330488929085, -0.0014834113617638867) => CYAN_TERRACOTTA,
    0x764656, (0.4554520435574629, 0.06902159676644007, -0.0015161272044461604) => PURPLE_TERRACOTTA,
    0x4A3B5B, (0.3819908613754922, 0.032617704231397565, -0.045958971229272616) => BLUE_TERRACOTTA,
    0x4D3223, (0.34526413453064436, 0.030069931896774177, 0.035494994373960365) => BROWN_TERRACOTTA,
    0x4C532A, (0.4253927315854246, -0.028234864834441348, 0.05524261234145378) => GREEN_TERRACOTTA,
    0x8E3C2E, (0.4639730270613335, 0.09776359273258214, 0.0601264977261754) => RED_TERRACOTTA,
    0x251610, (0.21828432648450805, 0.019995846833063283, 0.018406749695597135) => BLACK_TERRACOTTA,
]);
vanilla_table!(GLASS_TABLE, [
    0xF9FFFE, (0.9952267541729087, -0.00642632041602853, -0.0005938072511147974) => WHITE_STAINED_GLASS,
    0xF9801D, (0.7243783540040456, 0.10785301066727876, 0.1400023236447629) => ORANGE_STAINED_GLASS,
    0xC74EBD, (0.6227896964098021, 0.1750229577568611, -0.09681189305140575) => MAGENTA_STAINED_GLASS,
    0x3AB3DA, (0.7171404949734929, -0.08476154599521918, -0.08174782528386948) => LIGHT_BLUE_STAINED_GLASS,
    0xFED83D, (0.889626794971553, -0.012918621783681361, 0.16548847521319687) => YELLOW_STAINED_GLASS,
    0x80C71F, (0.7539833519404685, -0.13059133446238042, 0.14882514274629383) => LIME_STAINED_GLASS,
    0xF38BAA, (0.7561702798344626, 0.1302555789211447, 0.003546876511352992) => PINK_STAINED_GLASS,
    0x474F52, (0.4215182826075246, -0.008477561464597383, -0.0077006425756998564) => GRAY_STAINED_GLASS,
    0x9D9D97, (0.6942210219300027, -0.00246243700956128, 0.008248676306012115) => LIGHT_GRAY_STAINED_GLASS,
    0x169C9C, (0.6289937879664972, -0.10020612533512313, -0.026550547822836723) => CYAN_STAINED_GLASS,
    0x8932B8, (0.5057857244127223, 0.133054633364054, -0.1542999468207395) => PURPLE_STAINED_GLASS,
    0x3C44AA, (0.44260869437579925, 0.012151966789098245, -0.1607448804041251) => BLUE_STAINED_GLASS,
    0x835432, (0.49074718859118327, 0.044839507955902136, 0.06537635347483084) => BROWN_STAINED_GLASS,
    0x5E7C16, (0.5437072433306326, -0.07437223489521824, 0.10444141712664567) => GREEN_STAINED_GLASS,
    0xB02E26, (0.5036981199495045, 0.1479264776559768, 0.07962232845020062) => RED_STAINED_GLASS,
    0x1D1D21, (0.23244899610481348, 0.0020757759378686874, -0.0073398273328574015) => BLACK_STAINED_GLASS,
]);

impl BlockPalette {
    /// The 16 concrete blocks — the most saturated flat colours in vanilla.
    pub const CONCRETE: BlockPalette = BlockPalette::from_entries(&CONCRETE_TABLE);
    /// The 16 wools — the vanilla dye colours themselves.
    pub const WOOL: BlockPalette = BlockPalette::from_entries(&WOOL_TABLE);
    /// The 16 terracottas — muted, earthy versions of the dye hues.
    pub const TERRACOTTA: BlockPalette = BlockPalette::from_entries(&TERRACOTTA_TABLE);
    /// The 16 stained glasses — dye hues again, for see-through work.
    pub const GLASS: BlockPalette = BlockPalette::from_entries(&GLASS_TABLE);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The stored Oklab constants must be exactly what the conversion produces.
    ///
    /// They exist only because `Color::to_oklab` cannot run in a `const` (it
    /// needs `cbrt`), so they were generated by running it and pasting the
    /// output. This re-derives all 64 on every test run: if the conversion ever
    /// changes, or a hex is edited without regenerating its triple, this fails
    /// rather than quietly matching blocks against stale coordinates.
    #[test]
    fn stored_oklab_matches_the_conversion() {
        for (name, table) in [
            ("CONCRETE", &CONCRETE_TABLE),
            ("WOOL", &WOOL_TABLE),
            ("TERRACOTTA", &TERRACOTTA_TABLE),
            ("GLASS", &GLASS_TABLE),
        ] {
            for entry in table.iter() {
                let computed = entry.color.to_oklab();
                let (dl, da, db) = (
                    entry.oklab.l - computed.l,
                    entry.oklab.a - computed.a,
                    entry.oklab.b - computed.b,
                );
                assert!(
                    dl.abs() < 1e-12 && da.abs() < 1e-12 && db.abs() < 1e-12,
                    "{name} table: {} stores {:?} but converts to {:?}",
                    entry.block,
                    entry.oklab,
                    computed,
                );
            }
        }
    }

    /// A palette built at run time converts its entries once, up front — the
    /// same invariant, for user tables.
    #[test]
    fn user_palettes_convert_their_entries_on_construction() {
        let colour = Color::rgb_hex(0x123456);
        let palette = BlockPalette::new(&[(colour, blocks::BLUE_CONCRETE)]);
        assert_eq!(palette.entries()[0].oklab, colour.to_oklab());
    }
}
